[versions]
activityCompose = "1.8.0"
androidGradlePlugin = "8.1.2"
androidJunitJupiterPlugin = "1.9.3.0"
annotations = "6.0.53"
compose = "1.6.0-alpha07"
composeBom = "2023.10.00"
composeNavigation = "2.7.4"
constraintLayout = "2.1.4"
constraintLayoutCompose = "1.1.0-alpha13"
coreKtx = "1.12.0"
dependencyUpdatePlugin = "0.48.0"
grpc = "1.58.0"
grpcKotlin = "1.4.0"
junitJupiter = "5.10.0"
kotlin = "1.9.10"
kotlinX = "1.7.3"
ktlintPlugin = "11.6.0"
lifecycleRuntimeKtx = "2.6.2"
marerialThree = "1.2.0-alpha09"
protobuf = "3.24.3"
protobufPlugin = "0.9.4"
spotlessPlugin = "6.22.0"
systemStubsJupiter = "2.1.3"
versionCatalogUpdatePlugin = "0.8.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-constraint-layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
annotations-api = { module = "org.apache.tomcat:annotations-api", version.ref = "annotations" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-constraint-layout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintLayoutCompose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "marerialThree" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpcKotlin" }
grpc-okhttp = { module = "io.grpc:grpc-okhttp", version.ref = "grpc" }
grpc-protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobuf" }
grpc-protobuf-lite = { module = "io.grpc:grpc-protobuf-lite", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-testing = { module = "io.grpc:grpc-testing", version.ref = "grpc" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitJupiter" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinX" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinX" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
system-stubs-jupiter = { module = "uk.org.webcompere:system-stubs-jupiter", version.ref = "systemStubsJupiter" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-junit-jupiter = { id = "de.mannodermaus.android-junit5", version.ref = "androidJunitJupiterPlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
gradle-dependency-update = { id = "com.github.ben-manes.versions", version.ref = "dependencyUpdatePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotlessPlugin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdatePlugin" }
